name: Frontend deployment

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: .
        run: npm install

      - name: Build
        working-directory: .
        run: npm run build

      - name: Deploy frontend 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist